/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f4f5",
        "surface-variant": "#e1e3e4",
        "surface-dim": "#d9dadb",
        outline: "#727687",
        "on-primary-container": "#f8f7ff",
        secondary: "#425ca0",
        "on-tertiary-fixed-variant": "#832600",
        "on-surface": "#191c1d",
        "inverse-primary": "#b3c5ff",
        background: "#f8f9fa",
        "on-primary": "#ffffff",
        "surface-container": "#edeeef",
        "on-secondary-fixed-variant": "#284386",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-fixed": "#001849",
        "tertiary-fixed-dim": "#ffb59d",
        "secondary-fixed-dim": "#b3c5ff",
        "on-secondary": "#ffffff",
        surface: "#f8f9fa",
        "on-tertiary-container": "#fff6f4",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#191c1d",
        "secondary-fixed": "#dae1ff",
        "surface-tint": "#0054d6",
        "tertiary-container": "#cc4204",
        "on-tertiary-fixed": "#390c00",
        "on-surface-variant": "#424656",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3132",
        "tertiary-fixed": "#ffdbd0",
        "secondary-container": "#9bb4fe",
        "on-primary-fixed-variant": "#003fa4",
        "primary-fixed": "#dae1ff",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-container": "#294487",
        "on-primary-fixed": "#001849",
        "outline-variant": "#c2c6d8",
        "surface-container-high": "#e7e8e9",
        primary: "#0050cb",
        tertiary: "#a33200",
        "primary-container": "#0066ff",
        "primary-fixed-dim": "#b3c5ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
